#!/usr/bin/env python3
"""
Cookie Extractor for Multi-Format Video and Audio Downloader

A utility script to extract cookies from browsers and save them in Netscape format.
This can be used to bypass website restrictions when downloading videos.
"""

import os
import sys
import argparse
import json
import sqlite3
import shutil
import tempfile
import subprocess
from pathlib import Path
from datetime import datetime, timedelta

def check_dependencies():
    """Check if required dependencies are installed."""
    try:
        import browser_cookie3
        return True
    except ImportError:
        print("browser_cookie3 module not found. Installing...")
        try:
            subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'browser-cookie3'])
            return True
        except subprocess.CalledProcessError:
            print("Failed to install browser-cookie3. Please install it manually:")
            print("pip install browser-cookie3")
            return False

def extract_cookies_from_browser(browser, domain=None, output_file=None):
    """Extract cookies from the specified browser."""
    try:
        import browser_cookie3
        
        # Get the appropriate browser cookie jar
        if browser.lower() == 'chrome':
            cj = browser_cookie3.chrome()
        elif browser.lower() == 'firefox':
            cj = browser_cookie3.firefox()
        elif browser.lower() == 'safari':
            cj = browser_cookie3.safari()
        elif browser.lower() == 'edge':
            cj = browser_cookie3.edge()
        elif browser.lower() == 'opera':
            cj = browser_cookie3.opera()
        else:
            print(f"Unsupported browser: {browser}")
            return False
        
        # Filter cookies by domain if specified
        cookies = []
        for cookie in cj:
            if domain is None or domain in cookie.domain:
                cookies.append(cookie)
        
        if not cookies:
            print(f"No cookies found" + (f" for domain {domain}" if domain else ""))
            return False
        
        # Write cookies to file in Netscape format
        if output_file:
            with open(output_file, 'w') as f:
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# This file was generated by extract_cookies.py\n")
                f.write(f"# Created: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write("# ---------------------------------------------------------------\n")
                
                for cookie in cookies:
                    secure = "TRUE" if cookie.secure else "FALSE"
                    http_only = "TRUE" if cookie.has_nonstandard_attr('HttpOnly') else "FALSE"
                    expires = int((cookie.expires or 0))
                    
                    f.write(f"{cookie.domain}\t")
                    f.write("TRUE\t")  # domain_specified
                    f.write(f"{cookie.path}\t")
                    f.write(f"{secure}\t")
                    f.write(f"{expires}\t")
                    f.write(f"{cookie.name}\t")
                    f.write(f"{cookie.value}\n")
            
            print(f"Cookies saved to {output_file}")
            print(f"Total cookies: {len(cookies)}")
            return True
        else:
            # Print cookies to stdout
            print("# Netscape HTTP Cookie File")
            print("# This file was generated by extract_cookies.py")
            print(f"# Created: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
            print("# ---------------------------------------------------------------")
            
            for cookie in cookies:
                secure = "TRUE" if cookie.secure else "FALSE"
                http_only = "TRUE" if cookie.has_nonstandard_attr('HttpOnly') else "FALSE"
                expires = int((cookie.expires or 0))
                
                print(f"{cookie.domain}\tTRUE\t{cookie.path}\t{secure}\t{expires}\t{cookie.name}\t{cookie.value}")
            
            print(f"\nTotal cookies: {len(cookies)}")
            return True
    
    except Exception as e:
        print(f"Error extracting cookies: {e}")
        return False

def main():
    """Main function."""
    parser = argparse.ArgumentParser(description='Extract cookies from browsers for video downloading')
    
    parser.add_argument('browser', choices=['chrome', 'firefox', 'safari', 'edge', 'opera'],
                        help='Browser to extract cookies from')
    
    parser.add_argument('-d', '--domain', 
                        help='Filter cookies by domain (e.g., youtube.com)')
    
    parser.add_argument('-o', '--output', 
                        help='Output file to save cookies (default: stdout)')
    
    args = parser.parse_args()
    
    # Check dependencies
    if not check_dependencies():
        sys.exit(1)
    
    # Extract cookies
    success = extract_cookies_from_browser(args.browser, args.domain, args.output)
    
    if not success:
        sys.exit(1)

if __name__ == "__main__":
    main()